$(document).ajaxError(function(event, jqXHR, ajaxSettings, thrownError) {
        console.log('unknown ajax error: '+event);
    }
);

// insert text to active element
function setField(text) {
    chrome.tabs.executeScript(null, 
        {code:"document.activeElement.value = '"+text+"';"});
}

function findUserID(homepageHTML) {
    var re = /folders\/(\d*)\/name/;
    matches = homepageHTML.match(re);
    return matches[1];
}

//convert the page url to the appropriate sneakemail name to search/create
function urlToSneakemailName(url) {
    var domain = url.split('/')[2];
    var domains = domain.split('.');
    return domains[domains.length-2]+'.'+domains[domains.length-1];
}

// insert sneakemail address to active page element
function insertAddress(info, tab) {
    var emailLabel = urlToSneakemailName(info.pageUrl);
    setField(''+emailLabel+': Logging in...');
    //login
    $.ajax('https://sneakemail.com/public/auth', {
        type : 'post',
        data : credentials, //specified in auth.js file (see readme)
        success : function(data, textStatus, jqXHR) {
            var userID = findUserID(data);
            searchAddress(emailLabel, userID)
        },
        error : function() {
            console.log('failed on login call');
            setField('The bugfix is in the Castle of AAARRRGHHH...');
        },
    });
}

function searchAddress(emailLabel, userID){
    setField(''+emailLabel+': Searching...');
    
    $.ajax('https://sneakemail.com/folders/'+userID+'/name/find_names/'+emailLabel, {
        success : function(data, textStatus, jqXHR) {
            var $scratch = $('#scratchpad').html(data);
            var found = $scratch.find('#activate_address');
            if(found.size())
                setField(found.val());
            else
                createAddress($scratch, userID, emailLabel);
        },
        error : function() {
            console.log('failed on search');
            setField('Maybe the developer is pining for the fjords?');
        },
    });
}

function createAddress($newFormPage, userID, emailLabel){
    setField(''+emailLabel+': Creating...');
    
    var createData = {
        notes : 'auto-generated by Chrome extension',
        folder_pulldown : userID
    };
    $newFormPage.find('form:last input').each(function(index) {
        createData[this.name] = this.value;
    });
    
    var url = 'https://sneakemail.com'+$newFormPage.find('form:last').attr('action');
    
    $.ajax(url, {
        type : 'post',
        data : createData,
        success : function(data, textStatus, jqXHR) {
            var found = $('#scratchpad').html(data).find('#activate_address');
            if(found.size())
                setField(found.val());
            else {
                setField('And god said... Oops.'); //creation failed
            }
        },
        error : function() {
            console.log('failed on create');
            setField('1... 2... 5! (doh)');
        },
    });
}

//TODO: add content_script that creates this menu and calls an event into background page on click
//  That allows the background script to be non-persistent and use less memory
var title = "Sneakemail address here";
var id = chrome.contextMenus.create(
    {"title": title, "contexts":["editable"], "onclick": insertAddress},
    function() {
        if(chrome.extension.lastError) {
            console.log("menu item create error: " + chrome.extension.lastError.message);
        }
    }
    );
