$(document).ajaxError(function(event, jqXHR, ajaxSettings, thrownError) {
        console.log('unknown ajax error: '+event);
    }
);

function captureInputField(tab) {
    field = { tab: tab.id, fieldVar : 'sneakemail_generated_addr' }
    
    chrome.tabs.executeScript(field.tab, 
        {code : "document."+field.fieldVar+" = document.activeElement;"});
        
    return field;
}

// insert text to active element
function setField(field, text) {
    chrome.tabs.executeScript(field.tab, 
        {code:"document."+field.fieldVar+".value = '"+text+"';"});
}

function findUserID(homepageHTML) {
    var re = /folders\/(\d*)\/name/;
    matches = homepageHTML.match(re);
    if(!matches)
        return null;
    else
        return matches[1];
}

//convert the page url to the appropriate sneakemail name to search/create
function urlToSneakemailName(url) {
    var domain = url.split('/')[2];
    var domains = domain.split('.');
    return domains[domains.length-2]+'.'+domains[domains.length-1];
}

//Confirm username/password are saved
function isAuthAvailable(){
    return localStorage.username && localStorage.password;
}

// insert sneakemail address to active page element
function insertAddress(info, tab) {
    var field = captureInputField(tab);
    setField(field, 'Sneakemail Filler init...');
    
    if (!isAuthAvailable()){
        chrome.pageAction.show(tab.id);
        setField(field, 'Please add login and try again');
        return;
    }
    
    var emailLabel = urlToSneakemailName(info.pageUrl);
    setField(field, emailLabel+': Logging in...');
    login_info = {
        username : localStorage.username,
        password : localStorage.password,
        remember_me : "true"
    }
    //login
    $.ajax('https://sneakemail.com/public/auth', {
        type : 'post',
        data : login_info,
        success : function(data, textStatus, jqXHR) {
            var userID = findUserID(data);
            if(!userID) {
                chrome.pageAction.show(tab.id);
                setField(field, 'Sneakemail Login Failed');
            }
            else
                searchAddress(emailLabel, userID, field)
        },
        error : function() {
            console.log('failed on login call');
            setField(field, 'The bugfix is in the Castle of AAARRRGHHH...');
        },
    });
}

function searchAddress(emailLabel, userID, targetField){
    setField(targetField, emailLabel+': Searching...');
    
    $.ajax('https://sneakemail.com/folders/'+userID+'/name/find_names/'+emailLabel, {
        success : function(data, textStatus, jqXHR) {
            var $scratch = $('#scratchpad').html(data);
            var found = $scratch.find('#activate_address');
            if(found.size())
                setField(targetField, found.val());
            else
                createAddress($scratch, userID, emailLabel, targetField);
            $scratch.html('');
        },
        error : function() {
            console.log('failed on search');
            setField(targetField, 'Maybe the developer is pining for the fjords?');
        },
    });
}

function createAddress($newFormPage, userID, emailLabel, targetField){
    setField(targetField, emailLabel+': Creating...');
    
    var createData = {
        notes : 'auto-generated by Chrome extension',
        folder_pulldown : userID
    };
    $newFormPage.find('form:last input').each(function(index) {
        createData[this.name] = this.value;
    });
    
    var url = 'https://sneakemail.com'+$newFormPage.find('form:last').attr('action');
    
    $.ajax(url, {
        type : 'post',
        data : createData,
        success : function(data, textStatus, jqXHR) {
            var found = $('#scratchpad').html(data).find('#activate_address');
            if(found.size())
                setField(targetField, found.val());
            else {
                setField(targetField, 'And god said... Oops.'); //creation failed
            }
        },
        error : function() {
            console.log('failed on create');
            setField(targetField, '1... 2... 5! (doh)');
        },
    });
}

//TODO: add content_script that creates this menu and calls an event into background page on click
//  That allows the background script to be non-persistent and use less memory
var title = "Sneakemail address here";
var id = chrome.contextMenus.create(
    {"title": title, "contexts":["editable"], "onclick": insertAddress},
    function() {
        if(chrome.extension.lastError) {
            console.log("menu item create error: " + chrome.extension.lastError.message);
        }
    }
    );
